### ISSUE TITLE
Iteration #1

### ISSUE THREAD

**Issue by l-monninger** [gameday-guru/model-builder#2]
# Overview
The ultimate goal of the `model-builder` is to be an easy to use API for external developers. To get there, we need to make some changes. I use @maskrap97 as a guinea pig.

## Dataframes
Dataframes for state will make basic data analysis a lot easier.

## Streaming API
State should be streamable.

## Math Optimizations
Operations should be automatically optimized. Ideally GPU-driven (CUDA).

## Intelligently Design Dataframes Bespoke to Sports Compute
What can we do to make it as easy as possible to generate common sports statistics from state and others.

## Cosmetic Updates
Type inference etc.

## Codata Approach to Dataframes
This should be irrelevant to the end developer. But, this will help avoid issues with large datasets.

# Takeaways
1. @maskrap97,  if you can add any other headers for things that you think would be useful as specific improvements or as general guideposts, that would be great.

2. @maskrap97,  if you can generate a list of operations that you found yourself commonly performing, that would also be great.

**Comment by maskrap97** [comment]
1. Some time of data preview for once we have dataframes would be helpful; I'm not sure if this is already possible but it would be helpful to be able to write a task and then speed up time for testing to check for iterations
2. mostly basic operations (multiply, divide, add, subtract) and averages; for MLB we will likely need exponentials for a polynomial regression

Also, I think of the headers listed dataframes was the main one that came to mind when I was writing the model. Although I think all of them will be useful
